# Generated by Django 2.2.4 on 2019-10-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191028_0649'),
    ]

    # operations = [
    #     migrations.CreateModel(
    #         name='Image',
    #         fields=[
    #             ('id', models.BigAutoField(primary_key=True, serialize=False)),
    #             ('name', models.CharField(blank=True, max_length=150, null=True)),
    #         ],
    #     ),
    #     migrations.RemoveField(
    #         model_name='contactformmodel',
    #         name='phone',
    #     ),
    # ]
