# Generated by Django 2.2.4 on 2019-10-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_auto_20191028_0651'),
    ]

