# Generated by Django 2.0.12 on 2019-11-14 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_remove_contactformmodel_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='full_name',
            new_name='الاسم',
        ),
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='email',
            new_name='الرقم',
        ),
        migrations.RenameField(
            model_name='contactformmodel',
            old_name='description',
            new_name='الوصف',
        ),
    ]
