# Generated by Django 2.0.12 on 2019-11-14 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20191114_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='الرقم',
            field=models.CharField(max_length=12),
        ),
    ]
