# Generated by Django 2.0.12 on 2019-11-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20191117_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeimage',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
