# Generated by Django 2.0.12 on 2019-11-18 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20191117_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeimage',
            old_name='cover',
            new_name='image',
        ),
    ]
