# Generated by Django 2.0.12 on 2019-11-18 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_depart2'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='contactformmodel',
            table='التواصل',
        ),
    ]
