# Generated by Django 2.0.12 on 2019-11-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20191118_0305'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='depart1',
            table='الاعشاب',
        ),
        migrations.AlterModelTable(
            name='depart2',
            table='الرقية الشرعية',
        ),
        migrations.AlterModelTable(
            name='homeimage',
            table='الرئيسية',
        ),
    ]
