# Generated by Django 2.0.12 on 2019-11-18 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_auto_20191118_0325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'verbose_name': 'التواصل'},
        ),
    ]
