# Generated by Django 2.0.12 on 2019-11-18 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0023_auto_20191118_0340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactFormModel',
        ),
    ]
