# Generated by Django 2.0.12 on 2019-11-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0026_auto_20191118_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depart2',
            options={'verbose_name': 'قسم الرقية الشرعية'},
        ),
    ]
