# Generated by Django 2.0.12 on 2019-11-18 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0027_auto_20191118_0351'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactformmodel',
            options={'verbose_name': 'التواصل معنا', 'verbose_name_plural': 'التواصل'},
        ),
    ]
