# Generated by Django 2.0.12 on 2019-11-20 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0029_auto_20191118_0355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depart1',
            options={'verbose_name_plural': 'قسم علاج السحر والحسد والمس'},
        ),
    ]
