# Generated by Django 2.0.12 on 2019-11-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0030_auto_20191120_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Depart3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'قسم خواتم روحانيه',
            },
        ),
        migrations.CreateModel(
            name='Depart4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.TextField()),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'قسم جوهرة علم الروحانيات(هيلوت)',
            },
        ),
        migrations.AlterModelOptions(
            name='depart2',
            options={'verbose_name_plural': 'قسم الاعشاب النادرة'},
        ),
    ]
