# Generated by Django 2.0.12 on 2019-11-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0031_auto_20191120_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformmodel',
            name='الرقم',
            field=models.CharField(max_length=15),
        ),
    ]
