# Generated by Django 2.0.12 on 2019-12-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0036_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='video',
            field=models.URLField(),
        ),
    ]
