# Generated by Django 2.0.12 on 2019-12-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0038_auto_20191203_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='video',
            field=models.URLField(),
        ),
    ]
