# Generated by Django 2.0.12 on 2019-12-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0040_auto_20191203_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtube',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
