# Generated by Django 2.0.12 on 2019-12-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0043_auto_20191206_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='video',
            field=models.CharField(max_length=200),
        ),
    ]
