# Generated by Django 2.0.12 on 2019-12-06 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0044_auto_20191206_0912'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
